### ISSUE TITLE
DNS Admins

### ISSUE THREAD

**Issue by kberkheiser** [SpecterOps/TierZeroTable#1]
In the "Users (container)" section, it is mentioned that DNS Admins are Tier-0, but that group does not have a row in this table identifying it as Tier-0.

**Comment by kberkheiser** [comment]
Same for Cert Publishers.

**Comment by JonasBK** [comment]
Hi @kberkheiser,

Well spotted!

We mention that we see them as Tier Zero to justify having the Users container in Tier Zero. The plan is to cover them in detail in a future episode and then add them to the table.

**Comment by JonasBK** [comment]
@kberkheiser if you feel like submitting a pull request for adding the group then we can add them immediately.
Will also reopen the issue to track that need to get these groups added
