### ISSUE TITLE
Object ID for the Privileged Authentication Administrator in the Cypher query is incorrect

### ISSUE THREAD

**Issue by robertstrom** [SpecterOps/TierZeroTable#7]
The object ID for the Privileged Authentication Administrator role has the object ID for the Global Administrators in the Cypher query.

You've got the Template ID correct, but the Cypher query is a duplicate of the Global Admin Cypher query.

The correct object ID for the Privileged Authentication Administrator role is:

7BE44C8A-ADAF-4E2A-84D6-AB2649E08A13

https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference

Thanks very much for this BloodHound / SharpHound / AzureHound great work!

**Comment by robertstrom** [comment]
I think something got shifted somewhere. The next role down (Privileged Role Administrator) has the object ID for the Privileged Authentication Administrator. Probably a good idea to check them all.

**Comment by JonasBK** [comment]
Hey!

Copy-pasting gone wrong 🤦 

Thanks for reporting it - now fixed!
